spring:
  output:
    ansi:
      enabled: detect
  cache:
    type: jcache
    jcache:
      config: ehcache-cil.xml
server:
  tomcat:
    additional-tld-skip-patterns: xercesImpl.jar, xml-apis.jar, serializer.jar