spring:
  output:
    ansi:
      enabled: detect
  cache:
    type: jcache
    jcache:
      config: ehcache-cil.xml
logging:
  config: config/logback.xml

---

management:
  health:
    jms:
      enabled: false
server:
  tomcat:
    additional-tld-skip-patterns: xercesImpl.jar, xml-apis.jar, serializer.jar
  port: 8998